apiVersion: v1
kind: Service
metadata:
  name: hello-kube-service
  labels:
    app: hello-kube
spec:
  selector:
    app: hello-kube
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
